[build]
  publish = "."

[functions]
  directory = "functions"

[functions."register"]
  environment = ["MONGO_URI", "DB_NAME"]

# --- NUOVA REGOLA DI TEST (TEMPORANEA) ---
# Questa regola dovrebbe reindirizzare SEMPRE dash.html a index.html
# per vedere se il reindirizzamento base funziona.
[[redirects]]
  from = "/dash.html"
  to = "/index.html"
  status = 302
  force = true

# Rimuovi o commenta la tua vecchia regola:
# [[redirects]]
#   from = "/dash.html"
#   to = "/index.html"
#   status = 302
#   force = true
#   conditions = {Cookie = ["!streamverse_auth=true"]}
