[build]
  publish = "."

[functions]
  directory = "functions"

[functions."register"]
  environment = ["MONGO_URI", "DB_NAME"]

# --- SEZIONE DI PROTEZIONE (QUELLA COMPLETA) ---
[[redirects]]
  from = "/dash.html"  # La pagina che vuoi proteggere
  to = "/index.html"   # La tua pagina di login
  status = 302         # Reindirizzamento temporaneo
  force = true         # Forza il reindirizzamento

  # Questa è la condizione che deve funzionare!
  conditions = {Cookie = ["!streamverse_auth=true"]}

# Puoi aggiungere altre pagine protette qui, se necessario.
