[build]
  publish = "."

[functions]
  directory = "functions"

[functions."register"]
  environment = ["MONGO_URI", "DB_NAME"]

# --- INIZIO SEZIONE DI PROTEZIONE ---
# Questa regola reindirizza /dash.html a /index.html (login)
# se il cookie 'streamverse_auth=true' NON è presente.
[[redirects]]
  from = "dash.html"  # La pagina che vuoi proteggere
  to = "index.html"   # La tua pagina di login
  status = 302         # Reindirizzamento temporaneo
  force = true         # Forza il reindirizzamento

  # La condizione che verifica la presenza del cookie
  # Il nome del cookie e il valore devono corrispondere esattamente alla funzione!
  conditions = {Cookie = ["!streamverse_auth=true"]}

# Puoi aggiungere altre pagine protette qui, se necessario:
# [[redirects]]
#   from = "/altra-pagina.html"
#   to = "/index.html"
#   status = 302
#   force = true
#   conditions = {Cookie = ["!streamverse_auth=true"]}

# --- FINE SEZIONE DI PROTEZIONE ---
