[build]
  publish = "."

[functions]
  directory = "functions"

[functions."register"]
  environment = ["MONGO_URI", "DB_NAME"]

# --- NUOVA SEZIONE PER LA PROTEZIONE ---
[[redirects]]
  from = "/dash.html" # La pagina che vuoi proteggere
  to = "/index.html"  # La tua pagina di login
  status = 302        # Reindirizzamento temporaneo (puoi usare 301 per permanente)
  force = true        # Forza il reindirizzamento

  # Questa è la condizione: reindirizza solo se il cookie 'streamverse_auth' NON è presente
  # o se il suo valore non è 'true'.
  # Il nome del cookie deve corrispondere a quello che imposterai nella Netlify Function.
  conditions = {Cookie = ["!streamverse_auth=true"]}

# Puoi aggiungere altre pagine protette così:
# [[redirects]]
#   from = "/altra-pagina-protetta.html"
#   to = "/index.html"
#   status = 302
#   force = true
#   conditions = {Cookie = ["!streamverse_auth=true"]}

# --- FINE NUOVA SEZIONE ---
